runtime: python39
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
instance_class: F4_1G

env_variables:
  PROJECT_NAME: "fintech75"
  PROJECT_VERSION: "1.0.0"
  ON_CLOUD: "False"
  ACCESS_TOKEN_EXPIRE_MINUTES: "60"
  SECRET_KEY: "SECRET_SECRET_KEY"
  ALGORITHM: "SECRET_ALGORITHM"
  DB_SOCKET_DIR: "SECRET_DB_SOCKET_DIR"
  POSTGRES_SERVER: "SECRET_POSTGRES_SERVER"
  POSTGRES_PORT: "SECRET_POSTGRES_PORT"
  POSTGRES_DB: "SECRET_POSTGRES_DB"
  POSTGRES_USER: "SECRET_POSTGRES_USER"
  POSTGRES_PASSWORD: "SECRET_POSTGRES_PASSWORD"
  INSTANCE_CONNECTION_NAME: "SECRET_INSTANCE_CONNECTION_NAME"

handlers:
  - url: /.*
    script: main.app
    secure: always
