edge_1 = Edge(first_minutiae, second_minutiae)
    # edge_2 = Edge(second_minutiae, third_minutiae)
    # #edge_3 = Edge(third_minutiae, first_minutiae)
    # edge_3 = Edge(third_minutiae, fourth_minutiae)
    # edge_4 = Edge(fourth_minutiae, fifth_minutiae)
    # edge_5 = Edge(fifth_minutiae, sixth_minutiae)
    # edge_6 = Edge(sixth_minutiae, seventh_minutiae)
    # edge_7 = Edge(seventh_minutiae, eigth_minutiae)

    # edge_1.obtain_ratio(None)
    # edge_2.obtain_ratio(edge_1)
    # edge_3.obtain_ratio(edge_2)
    # edge_4.obtain_ratio(edge_3)
    # edge_5.obtain_ratio(edge_4)
    # edge_6.obtain_ratio(edge_5)
    # edge_7.obtain_ratio(edge_6)

    # edge_1.obtain_angle(None)
    # edge_2.obtain_angle(edge_1)
    # edge_3.obtain_angle(edge_2)
    # edge_4.obtain_angle(edge_3)
    # edge_5.obtain_angle(edge_4)
    # edge_6.obtain_angle(edge_5)
    # edge_7.obtain_angle(edge_6)